# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomGen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trick',
            name='family',
            field=models.CharField(choices=[('top', 'top'), ('aerials', 'aerials'), ('around', 'around'), ('sonic', 'sonic'), ('shadow', 'shadow'), ('tap', 'tap'), ('pass', 'pass'), ('other', 'other')], default='top', max_length=20),
        ),
        migrations.AddField(
            model_name='trick',
            name='position_choices',
            field=models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('12', '12'), ('13', '13'), ('14', '14'), ('23', '23'), ('24', '24'), ('34', '34')], default='T1', max_length=2),
        ),
    ]
