# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomGen', '0006_auto_20160806_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trick',
            old_name='family',
            new_name='family_choices',
        ),
        migrations.AddField(
            model_name='trick',
            name='orient_choices',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Reverse', 'Reverse')], default='Normal', max_length=10),
        ),
    ]
