# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomGen', '0007_auto_20160806_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='trick',
            name='direction_choices',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Reverse', 'Reverse')], default='Normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='trick',
            name='orient_choices',
            field=models.CharField(choices=[('Down', 'Down'), ('Up', 'Up'), ('Side', 'Side'), ('All', 'All')], default='All', max_length=10),
        ),
    ]
